alias reload!='. ~/.zshrc'
alias gpp='git pull --rebase && git push'
alias gmf='git merge --ff-only'
alias gap='git add --patch'
alias e='open -a Emacs $*'
alias ec='emacsclient -n $*'
alias vi='nvim'